/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_ni240sx_ucgt_compression_Compression */

#ifndef _Included_fr_ni240sx_ucgt_compression_Compression
#define _Included_fr_ni240sx_ucgt_compression_Compression
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jboolean JNICALL Java_fr_ni240sx_ucgt_compression_Compression_pluginInit();

/*
 * Class:     fr_ni240sx_ucgt_compression_Compression
 * Method:    decompressPlugin
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_fr_ni240sx_ucgt_compression_Compression_decompressPlugin
  (JNIEnv *env, jclass _class, jbyteArray arr);

#ifdef __cplusplus
}
#endif
#endif
